spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 6a61020f9ca172e1284f86a2743e6b98 # SecurityConfig에 하드코딩된 클라이언트 ID와 일치해야 함
            client-secret: vPKEBYN2YpQIWThY79deYzO29qH6QEoi # 카카오 개발자 사이트에서 발급받은 Secret
            client-authentication-method: client_secret_post # 카카오에서 권장하는 방식 중 하나
            authorization-grant-type: authorization_code # 웹 애플리케이션 표준 방식
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}" # Spring Security 기본 리다이렉트 URI 패턴
            scope: profile_nickname, profile_image, account_email # 카카오에서 받아올 사용자 정보 범위 (필요에 따라 조정)

        provider:
          # 카카오 공급자 정보 (registrationId와 이름 일치: kakao)
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize # 카카오 인증 서버 URL
            token-uri: https://kauth.kakao.com/oauth/token # 카카오 토큰 발급 URL
            user-info-uri: https://kapi.kakao.com/v2/user/me # 카카오 사용자 정보 조회 URL
            user-name-attribute: id # 사용자 정보 응답에서 고유 식별자로 사용할 속성 이름 (카카오는 보통 'id')

  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/SE?serverTimezone=UTC&characterEncoding=UTF-8
      username: kimseonmin
      password: 1234


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.dr.domain
  configuration:
    map-underscore-to-camel-case: true
#  logging:
#    level:
#      org.apache.ibatis: DEBUG
#      org.springframework.jdbc: DEBUG
#      com.dr.mapper: DEBUG # Mapper 인터페이스 패키지
openai:
  api:
    key: sk-proj—mXp1ldv4HeHGhlfys2aUy90BOgU2BmwWuOlQq2tdhRr8cy0LJ1Jxc7o8aJ9wP15eidkQ0pZTWT3BlbkFJRzPzdP2onFdkNNBCY467ijuVWdbHU0ttY_APWZpx-A2zBLT3oLq5KX8XWYbSKMdg2ptwlMBgUA
    url: https://api.openai.com/v1/chat/completions # 새로 추가
coolsms:
  api:
    key: NCSBV849NEG60GKW # CoolSMS 웹사이트에서 발급받은 API Key
    secret: J4726P0JAGUMVQROZIYVVUG7XSFFSTEH # CoolSMS 웹사이트에서 발급받은 API Secret
    number: 010-4158-0566 # CoolSMS에 등록된 발신 번호 (하이픈 포함 또는 제외)