-- 테스트 데이터 삭제
DELETE FROM DR_MANAGER WHERE MANAGER_NUMBER = 1;

-- 테스트 데이터 삽입
INSERT INTO DR_MANAGER (MANAGER_NUMBER, MANAGER_EMAIL, MANAGER_PW, MANAGER_NAME, MANAGER_SORT)
VALUES (1, 'manager1@dr.com', 'password1!', '송아성', 'ADMIN');