-- test-dashboard.sql

-- Delete data potentially conflicting with dashboard test (IDs 1-60 assumed)
-- Delete child table data first (using simplified WHERE clauses for clarity, adjust ranges if needed)
DELETE FROM DR_REPLY WHERE REPLY_NUMBER BETWEEN 1 AND 100; -- Assuming replies up to 100 might conflict
DELETE FROM DR_GOOD WHERE GOOD_NUMBER IS NOT NULL; -- Or use specific ranges if known
DELETE FROM DR_SIREN WHERE SIREN_NUMBER IS NOT NULL; -- Or use specific ranges if known
DELETE FROM DR_POINT WHERE POINT_NUMBER BETWEEN 1 AND 200; -- Assuming points up to 200 might conflict
DELETE FROM DR_DAILY WHERE USER_NUMBER BETWEEN 1 AND 60;
DELETE FROM DR_CHAT WHERE CHAT_NUMBER IS NOT NULL; -- Or use specific ranges if known
DELETE FROM DR_CHAT_SESSION WHERE SESSION_NUMBER IS NOT NULL; -- Or use specific ranges if known
DELETE FROM DR_BOARD WHERE BOARD_NUMBER BETWEEN 1 AND 20; -- Assuming boards up to 20 might conflict
DELETE FROM DR_RECIPE WHERE RECIPE_NUMBER BETWEEN 1 AND 7; -- Assuming recipes up to 7 might conflict
DELETE FROM DR_MANAGER WHERE MANAGER_NUMBER = 1; -- Delete manager if re-inserting
-- Delete users last
DELETE FROM DR_USER WHERE USER_NUMBER BETWEEN 1 AND 60;

-- Insert test data for dashboard: userAll=60, numAll=2 (1 board + 1 recipe)
-- Insert 60 Users (Example: first and last shown, need 60 total)
-- Insert 60 Users for dashboard test (userAll=60)
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (1, 'user1@example.com', 'pw1', '닉네임1', '010-0001-0001', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (2, 'user2@example.com', 'pw2', '닉네임2', '010-0002-0002', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (3, 'user3@example.com', 'pw3', '닉네임3', '010-0003-0003', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (4, 'user4@example.com', 'pw4', '닉네임4', '010-0004-0004', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (5, 'user5@example.com', 'pw5', '닉네임5', '010-0005-0005', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (6, 'user6@example.com', 'pw6', '닉네임6', '010-0006-0006', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (7, 'user7@example.com', 'pw7', '닉네임7', '010-0007-0007', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (8, 'user8@example.com', 'pw8', '닉네임8', '010-0008-0008', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (9, 'user9@example.com', 'pw9', '닉네임9', '010-0009-0009', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (10, 'user10@example.com', 'pw10', '닉네임10', '010-0010-0010', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (11, 'user11@example.com', 'pw11', '닉네임11', '010-0011-0011', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (12, 'user12@example.com', 'pw12', '닉네임12', '010-0012-0012', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (13, 'user13@example.com', 'pw13', '닉네임13', '010-0013-0013', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (14, 'user14@example.com', 'pw14', '닉네임14', '010-0014-0014', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (15, 'user15@example.com', 'pw15', '닉네임15', '010-0015-0015', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (16, 'user16@example.com', 'pw16', '닉네임16', '010-0016-0016', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (17, 'user17@example.com', 'pw17', '닉네임17', '010-0017-0017', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (18, 'user18@example.com', 'pw18', '닉네임18', '010-0018-0018', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (19, 'user19@example.com', 'pw19', '닉네임19', '010-0019-0019', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (20, 'user20@example.com', 'pw20', '닉네임20', '010-0020-0020', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (21, 'user21@example.com', 'pw21', '닉네임21', '010-0021-0021', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (22, 'user22@example.com', 'pw22', '닉네임22', '010-0022-0022', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (23, 'user23@example.com', 'pw23', '닉네임23', '010-0023-0023', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (24, 'user24@example.com', 'pw24', '닉네임24', '010-0024-0024', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (25, 'user25@example.com', 'pw25', '닉네임25', '010-0025-0025', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (26, 'user26@example.com', 'pw26', '닉네임26', '010-0026-0026', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (27, 'user27@example.com', 'pw27', '닉네임27', '010-0027-0027', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (28, 'user28@example.com', 'pw28', '닉네임28', '010-0028-0028', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (29, 'user29@example.com', 'pw29', '닉네임29', '010-0029-0029', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (30, 'user30@example.com', 'pw30', '닉네임30', '010-0030-0030', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (31, 'user31@example.com', 'pw31', '닉네임31', '010-0031-0031', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (32, 'user32@example.com', 'pw32', '닉네임32', '010-0032-0032', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (33, 'user33@example.com', 'pw33', '닉네임33', '010-0033-0033', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (34, 'user34@example.com', 'pw34', '닉네임34', '010-0034-0034', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (35, 'user35@example.com', 'pw35', '닉네임35', '010-0035-0035', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (36, 'user36@example.com', 'pw36', '닉네임36', '010-0036-0036', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (37, 'user37@example.com', 'pw37', '닉네임37', '010-0037-0037', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (38, 'user38@example.com', 'pw38', '닉네임38', '010-0038-0038', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (39, 'user39@example.com', 'pw39', '닉네임39', '010-0039-0039', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (40, 'user40@example.com', 'pw40', '닉네임40', '010-0040-0040', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (41, 'user41@example.com', 'pw41', '닉네임41', '010-0041-0041', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (42, 'user42@example.com', 'pw42', '닉네임42', '010-0042-0042', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (43, 'user43@example.com', 'pw43', '닉네임43', '010-0043-0043', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (44, 'user44@example.com', 'pw44', '닉네임44', '010-0044-0044', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (45, 'user45@example.com', 'pw45', '닉네임45', '010-0045-0045', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (46, 'user46@example.com', 'pw46', '닉네임46', '010-0046-0046', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (47, 'user47@example.com', 'pw47', '닉네임47', '010-0047-0047', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (48, 'user48@example.com', 'pw48', '닉네임48', '010-0048-0048', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (49, 'user49@example.com', 'pw49', '닉네임49', '010-0049-0049', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (50, 'user50@example.com', 'pw50', '닉네임50', '010-0050-0050', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (51, 'user51@example.com', 'pw51', '닉네임51', '010-0051-0051', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (52, 'user52@example.com', 'pw52', '닉네임52', '010-0052-0052', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (53, 'user53@example.com', 'pw53', '닉네임53', '010-0053-0053', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (54, 'user54@example.com', 'pw54', '닉네임54', '010-0054-0054', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (55, 'user55@example.com', 'pw55', '닉네임55', '010-0055-0055', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (56, 'user56@example.com', 'pw56', '닉네임56', '010-0056-0056', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (57, 'user57@example.com', 'pw57', '닉네임57', '010-0057-0057', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (58, 'user58@example.com', 'pw58', '닉네임58', '010-0058-0058', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (59, 'user59@example.com', 'pw59', '닉네임59', '010-0059-0059', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (60, 'user60@example.com', 'pw60', '닉네임60', '010-0060-0060', '일반회원');
-- Insert 1 Board Post (to contribute 1 to numAll)
INSERT INTO DR_BOARD (BOARD_NUMBER, USER_NUMBER, BOARD_TITLE, BOARD_TEXT, BOARD_WRITE_DATE, BOARD_TYPE) VALUES (1, 1, 'Dashboard Board 1', 'Content for dashboard', NOW(), '자유게시판'); -- Ensure '자유게시판' is valid
INSERT INTO DR_BOARD (BOARD_NUMBER, USER_NUMBER, BOARD_TITLE, BOARD_TEXT, BOARD_WRITE_DATE, BOARD_TYPE) VALUES (2, 1, 'Dashboard Board 2', 'Content for dashboard', NOW(), '자유게시판'); -- Ensure '자유게시판' is valid

-- Insert 1 Recipe Post (to contribute 1 to numAll, total numAll = 2)
INSERT INTO DR_RECIPE (RECIPE_NUMBER, USER_NUMBER, RECIPE_TITLE, RECIPE_TEXT, RECIPE_WRITE_DATE) VALUES (1, 2, 'Dashboard Recipe 1', 'Recipe content for dashboard', NOW());

-- Insert Manager
INSERT INTO DR_MANAGER (MANAGER_NUMBER, MANAGER_EMAIL, MANAGER_PW, MANAGER_NAME, MANAGER_SORT) VALUES (1, 'manager1@dr.com', 'password1!', '송아성', 'ADMIN');