-- test-manage-user.sql

-- Delete data related to users 11-15 for test isolation
-- Delete child table data first
DELETE FROM DR_REPLY WHERE USER_NUMBER BETWEEN 11 AND 15;
DELETE FROM DR_BOARD WHERE USER_NUMBER BETWEEN 11 AND 15;
DELETE FROM DR_RECIPE WHERE USER_NUMBER BETWEEN 11 AND 15;
DELETE FROM DR_GOOD WHERE USER_NUMBER BETWEEN 11 AND 15;
DELETE FROM DR_SIREN WHERE USER_NUMBER BETWEEN 11 AND 15;
DELETE FROM DR_STEAM WHERE USER_NUMBER BETWEEN 11 AND 15;
DELETE FROM DR_SCORE WHERE USER_NUMBER BETWEEN 11 AND 15;
DELETE FROM DR_POINT WHERE USER_NUMBER BETWEEN 11 AND 15;
DELETE FROM DR_DAILY WHERE USER_NUMBER BETWEEN 11 AND 15;
DELETE FROM DR_CHAT WHERE USER_NUMBER BETWEEN 11 AND 15;
DELETE FROM DR_CHAT_SESSION WHERE USER_NUMBER BETWEEN 11 AND 15;
-- Add other child tables if necessary...

-- Delete the users last
DELETE FROM DR_USER WHERE USER_NUMBER BETWEEN 11 AND 15;

-- Insert test data: 4 users needed for manageUser test (expects userList.get(3))
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (11, 'user11@example.com', 'pw11', '닉네임1', '010-1111-1111', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (12, 'user12@example.com', 'pw12', '닉네임2', '010-2222-2222', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (13, 'user13@example.com', 'pw13', '닉네임3', '010-3333-3333', '일반회원');
INSERT INTO DR_USER (USER_NUMBER, USER_EMAIL, USER_PW, USER_NICKNAME, USER_PHONE, USER_STATUS) VALUES (14, 'user14@example.com', 'pw14', '닉네임4', '010-4444-4444', '일반회원'); -- 4번째 사용자