# .github/workflows/ci.yml

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ] # "main" 또는 실제 사용하는 주 브랜치명으로 확인
  pull_request:
    branches: [ "master" ] # "main" 또는 실제 사용하는 주 브랜치명으로 확인

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }} # 이것만 남겨봄
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        env: # <--- 테스트 실행 시 사용할 환경 변수 추가!
          SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/SE?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
          SPRING_DATASOURCE_USERNAME: ${{ secrets.TEST_DB_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          # SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop # 또는 validate, update (필요에 따라)
          # 또는 Flyway/Liquibase를 사용한다면 해당 설정
        run: ./gradlew build