# .github/workflows/ci.yml

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          MYSQL_DATABASE: SE
          MYSQL_USER: ${{ secrets.TEST_DB_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
        ports:
          - 3306:3306
        # options: >-  # <--- 이 options 부분을 단순화하거나, healthcheck를 다음 스텝으로 옮김
        #   --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -p${{ secrets.TEST_DB_PASSWORD }} --silent" # 이 부분이 문제의 원인
        #   --health-interval=10s
        #   --health-timeout=5s
        #   --health-retries=10
        # MySQL 8.0 이미지는 자체적으로 HEALTHCHECK를 가지고 있을 수 있습니다.
        # 명시적인 options healthcheck를 제거하고, 다음 스텝에서 연결을 시도하며 대기하는 방식으로 변경합니다.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Install MySQL client and Wait for MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          echo "Waiting for MySQL service to be ready..."
          # health-cmd를 여기서 실행하며, 비밀번호는 환경 변수로 전달
          timeout 60 bash -c 'until mysqladmin ping -h 127.0.0.1 -u root -p"$DB_ROOT_PASSWORD" --silent; do sleep 1; done'
        env:
          DB_ROOT_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}

      - name: Apply database schema
        run: |
          echo "Applying database schema..."
          mysql -h 127.0.0.1 -u root -p"$DB_ROOT_PASSWORD" SE < ./YOUR_SCHEMA_FILE_PATH # 실제 스키마 파일 경로로 수정
        env:
          DB_ROOT_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}

      - name: Build with Gradle
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/SE?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
          SPRING_DATASOURCE_USERNAME: ${{ secrets.TEST_DB_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          SPRING_JPA_HIBERNATE_DDL_AUTO: validate
        run: |
          echo "DB URL: $SPRING_DATASOURCE_URL"
          echo "DB User: $SPRING_DATASOURCE_USERNAME"
          ./gradlew build